spring:
  application:
    name : api-franquicias
  r2dbc:
    url: r2dbc:mysql://localhost:3306/franquicias_db
    username: root
    password: admin
    pool:
      max-size: 10
      max-idle-time: 30m